name: 'dbt-cloud-download-artifacts-action'
description: 'Download artifacts from a dbt Cloud CI job.'
inputs:
  commit-sha:
    description: 'SHA of the commit that triggered the dbt Cloud CI job.'
    required: true
  dbt-cloud-api-token:
    description: 'dbt Cloud API token.'
    required: true
  dbt-cloud-api-url-base:
    default: 'cloud.getdbt.com'
    description: 'Base URL of the dbt Cloud API.'
    required: false
  output-dir:
    default: '.'
    description: 'Directory where the artifacts will be saved.'
    required: false
  repo-name:
    default: '${{ github.repository }}'
    description: 'Name of the repository.'
    required: false
  step:
    default: ""
    description: 'The index of the Step in the Run to query for artifacts.'
    required: false
  verbose:
    default: 'false'
    description: Run dbt-cloud-download-artifacts-action in verbose mode.
    required: false

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      shell: bash
      run: uv python install

    - name: Install dependencies
      shell: bash
      run: uv venv && source .venv/bin/activate && make install

    - name: Assemble `step` parameter
      id: assemble-step-param
      shell: bash
      run: >
        if [[ "${{ inputs.step }}" = "" ]]; then
          echo "step-param=" >> $GITHUB_OUTPUT
        else
          echo "step-param=--step ${{ inputs.step }}" >> $GITHUB_OUTPUT
        fi

    - name: Assemble `verbose` parameter
      id: assemble-verbose-param
      shell: bash
      run: >
        if [[ "${{ inputs.verbose }}" = "false" ]]; then
          echo "verbose-param=" >> $GITHUB_OUTPUT
        else
          echo "verbose-param=--verbose" >> $GITHUB_OUTPUT
        fi

    - name: Download artifacts
      env:
        DBT_CLOUD_API_URL_BASE: ${{ inputs.dbt-cloud-api-url-base }}
        DBT_CLOUD_API_TOKEN: ${{ inputs.dbt-cloud-api-token }}
        PAT_GITHUB: ${{ github.token }}
      shell: bash
      run: |
        uv run download_artifacts \
          --commit-sha ${{ inputs.commit-sha }} \
          --output-dir ${{ inputs.output-dir }} \
          --repo-name ${{ inputs.repo-name }} ${{ steps.assemble-step-param.outputs.step-param }} ${{ steps.assemble-verbose-param.outputs.verbose-param }}
