name: 'dbt-cloud-download-artifacts-action'
description: 'Download artifacts from a dbt Cloud CI job.'
inputs:
  commit-sha:
    description: 'SHA of the commit that triggered the dbt Cloud CI job.'
    required: true
  output-dir:
    default: '.'
    description: 'Directory where the artifacts will be saved.'
    required: false
  step:
    default: ""
    description: 'The index of the Step in the Run to query for artifacts.'
    required: false
  verbose:
    default: 'false'
    description: Run dbt-cloud-download-artifacts-action in verbose mode.
    required: false

runs:
  using: composite

  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v2

    - name: Set up Python
      shell: bash
      run: uv python install $(cat .python-version)

    - name: Assemble `step` parameter
      id: assemble-step-param
      shell: bash
      run: >
        if [[ "${{ inputs.step }}" = "" ]]; then
          echo "step-param=" >> $GITHUB_OUTPUT
        else
          echo "step-param=--step ${{ inputs.step }}" >> $GITHUB_OUTPUT
        fi

    - name: Assemble `verbose` parameter
      id: assemble-verbose-param
      shell: bash
      run: >
        if [[ "${{ inputs.verbose }}" = "" ]]; then
          echo "verbose-param=" >> $GITHUB_OUTPUT
        else
          echo "verbose-param=--verbose" >> $GITHUB_OUTPUT
        fi

    - name: Download artifacts
      shell: bash
      run: |
        uvx \
          --from dbt-cloud-download-artifacts-action download_artifacts \
          --commit-sha ${{ inputs.commit-sha }} \
          --output-dir ${{ inputs.output-dir }} ${{ steps.assemble-verbose-param.outputs.verbose-param }} ${{ steps.assemble-verbose-param.outputs.verbose-param }}
