name: CI pipeline

on:
  pull_request:
      branches:
          - main

jobs:
    download-artifacts:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
          - name: Download dbt artifacts
            uses: pgoslatara/dbt-cloud-download-artifacts-action@v0
            with:
              commit-sha: ${{ github.sha }}
              dbt_cloud_api_token: ${{ secrets.DBT_CLOUD_API_TOKEN }}
              output-dir: target # Optional: Defaults to ".".
              step: 4 # Optional: Defaults to last step in CI job.
              verbose: true # Optional: Defaults to false.

          - run: ls -ahl target
