---
name: CI pipeline

on:
  pull_request_target:
      branches:
          - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DBT_PROFILES_DIR: dbt_project
  DBT_PROJECT_DIR: dbt_project
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: "0"

            - name: checkout-merge
              uses: check-spelling/checkout-merge@v0.0.5

            - name: Install uv
              uses: astral-sh/setup-uv@v2

            - name: Set up Python
              run: uv python install

            - name: Install dependencies
              run: uv venv && source .venv/bin/activate && make install

            - name: Run pre-commit
              run: |
                git diff --name-status origin/main..HEAD > changed_files.txt
                cat changed_files.txt
                cat changed_files.txt | xargs uv run pre-commit run --files

    unit-tests:
        needs: [pre-commit]
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
            issues: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4

            - name: checkout-merge
              uses: check-spelling/checkout-merge@v0.0.5

            - name: Install uv
              uses: astral-sh/setup-uv@v2

            - name: Set up Python
              run: uv python install

            - name: Install dependencies
              run: uv venv && source .venv/bin/activate && make install

            - name: Run pytest (unit tests)
              run: make test | tee pytest-coverage.txt && exit ${PIPESTATUS[0]}

            - name: Pytest coverage comment
              uses: MishaKav/pytest-coverage-comment@main
              with:
                  pytest-coverage-path: ./pytest-coverage.txt
                  title: Coverage Report
                  badge-title: Coverage
                  junitxml-path: ./coverage.xml
