---
name: Post-merge pipeline

on:
    push:
        branches:
            - main

jobs:
    create-and-poll-new-pr:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                    token: ${{ secrets.PAT_GITHUB }}

            - name: Dummy changes to force pipeline to detect some predicatable changes
              run: touch ./test.txt

            - name: Delete remote `test-action` branch
              run: git push origin --delete test-action || true

            - uses: EndBug/add-and-commit@v9
              with:
                    author_name: github-actions[bot]
                    author_email: bot@github.com
                    new_branch: test-action
                    push: --force --set-upstream origin test-action

            # To ensure the PR triggers CI workflows it needs to use someone's PAT instead of the default GITHUB_TOKEN
            - name: Create Pull Request
              id: create-ci-pr
              run: |
                    export PR_URL=$(gh pr create -B main -H test-action --title 'DO NOT MERGE: Auto-generated PR to run checks for PR ${{ github.event.number }}' --body 'Do not merge this PR')
                    echo "PR_URL=$PR_URL" >> $GITHUB_OUTPUT

            - name: Poll checks of triggered PR
              run: |
                    sleep 10 # Need to wait for PR to be initialised
                    export PR_NUM=$(echo "${{ steps.create-ci-pr.outputs.PR_URL }}" | cut -d / -f 7)
                    echo $PR_NUM
                    gh pr checks $PR_NUM --fail-fast --watch

    close-new-pr:
        if: always()
        needs: [create-and-poll-new-pr]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Close PR
              run: gh pr close ${{ github.event.number }}
