---
name: Post-merge pipeline

on:
    push:
        branches:
            - main

env:
    GH_TOKEN: ${{ secrets.PAT_GITHUB }}

jobs:
    create-and-poll-new-pr:
        outputs:
          pr_num: ${{ steps.poll-pr.outputs.PR_NUM }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                    token: ${{ secrets.PAT_GITHUB }}

            - name: Create `test-main` branch
              run: |
                git push origin --delete test-action || true
                git checkout -b test-main
                git push origin test-main

            - name: Dummy changes to force pipeline to detect some predicatable changes
              run: |
                sed -i 's/pull_request_target/pull_request/g' .github/workflows/ci_pipeline.yml
                touch ./test.txt

            - name: Delete remote `test-action` branch
              run: git push origin --delete test-action || true

            - uses: EndBug/add-and-commit@v9
              with:
                    author_name: github-actions[bot]
                    author_email: bot@github.com
                    new_branch: test-action
                    push: --force --set-upstream origin test-action

            - name: Create Pull Request
              id: create-ci-pr
              run: |
                    export PR_URL=$(gh pr create -B test-main -H test-action --title 'DO NOT MERGE: Auto-generated PR to run checks for commit ${{ github.sha }}' --body 'Do not merge this PR')
                    echo "PR_URL=$PR_URL" >> $GITHUB_OUTPUT

            - name: Poll checks of triggered PR
              id: poll-pr
              run: |
                    sleep 10 # Need to wait for PR to be initialised
                    export PR_NUM=$(echo "${{ steps.create-ci-pr.outputs.PR_URL }}" | cut -d / -f 7)
                    echo $PR_NUM
                    echo "PR_NUM=$PR_NUM" >> $GITHUB_OUTPUT
                    gh pr checks $PR_NUM --fail-fast --watch

    close-new-pr:
        if: always()
        needs: [create-and-poll-new-pr]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Close PR
              env:
                PR_NUM: ${{ needs.create-and-poll-new-pr.outputs.pr_num }}
              run: gh pr close $PR_NUM
