---
  name: Release pipeline

  on:
      workflow_dispatch:
          inputs:
              version_bump_type:
                  description: The version bump type to perform.
                  required: true
                  type: choice
                  options:
                      - major
                      - minor
                      - patch
                      - premajor
                      - preminor
                      - prepatch
                      - prerelease

  jobs:
      release:
          environment:
              name: publish
              url: https://pypi.org/p/dbt-cloud-download-artifacts-action
          runs-on: ubuntu-latest
          permissions:
              contents: write
              id-token: write
              packages: write
          steps:
              - uses: actions/checkout@v4

              - name: Install uv
                uses: astral-sh/setup-uv@v2

              - name: Set up Python
                run: uv python install

              - name: Install package
                run: uv venv && source .venv/bin/activate && make install

              - name: Get version and bump
                id: version
                run: |
                  export CURRENT_VERSION=$(uvx --from dbt-cloud-download-artifacts-action download_artifacts --version)
                  echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
                  echo "CURRENT_VERSION: $CURRENT_VERSION"
                  export VERSION=$(uvx --from semver==3.0.2 pysemver bump ${{ inputs.version_bump_type }} $CURRENT_VERSION)
                  echo "VERSION=$VERSION" >> $GITHUB_ENV
                  echo "VERSION: $VERSION"
                  uvx --from toml-cli==0.7.0 toml set --toml-path=pyproject.toml project.version $VERSION
                  echo "major=$(echo $(echo $VERSION | cut -d '.' -f 1))" >> $GITHUB_OUTPUT
                  echo "minor=$(echo $(echo $VERSION | cut -d '.' -f 2))" >> $GITHUB_OUTPUT
                  echo "patch=$(echo $(echo $VERSION | cut -d '.' -f 3))" >> $GITHUB_OUTPUT

              - name: Build whl file
                run: uv build

              - name: Determine if prerelease flag is necessary
                run: |
                    [ "${{ inputs.version_bump_type }}" = "premajor" ] || [ "${{ inputs.version_bump_type }}" = "preminor" ] || [ "${{ inputs.version_bump_type }}" = "prepatch" ] || [ "${{ inputs.version_bump_type }}" = "prerelease" ] && export PRERELEASE="--prerelease" || export PRERELEASE="--latest"
                    echo "PRERELEASE: $PRERELEASE"
                    echo PRERELEASE=$PRERELEASE >> "$GITHUB_ENV"

              - name: Tag commit and push
                run: |
                  git config --global user.email "bot@github.com"
                  git config --global user.name "github-actions[bot]"
                  git add -A
                  git commit -m "Bumping version to $VERSION"

                  # Tag and push X.X.X
                  git tag -f \
                    -a $VERSION \
                    -m "$VERSION"
                  git push -f origin "$VERSION"

                  # Tag and push X.X
                  git tag -f \
                    -a ${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }} \
                    -m "${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}"
                  git push -f origin "${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}"

                  # Tag and push X.X.X
                  git tag -f \
                    -a ${{ steps.version.outputs.major }} \
                    -m "${{ steps.version.outputs.major }}"
                  git push -f origin "${{ steps.version.outputs.major }}"

                  git push origin main

              - name: Publish package distributions to PyPI
                uses: pypa/gh-action-pypi-publish@release/v1
                with:
                  packages-dir: dist/

              - name: Create release
                env:
                    GH_TOKEN: ${{ secrets.PAT_GITHUB }}
                run: |
                    export LAST_RELEASE=$(gh release list --repo ${{ github.repository }} --order desc --json name --limit 1 | jq -r '.[0].name')
                    echo $LAST_RELEASE
                    gh release create $VERSION \
                        --generate-notes \
                        --repo ${{ github.repository }} \
                        --notes-start-tag $LAST_RELEASE \
                        --target main \
                        --title "$VERSION" \
                        $PRERELEASE

              - name: Upload .whl to release
                env:
                    GH_TOKEN: ${{ github.token }}
                run: gh release upload $VERSION ./dist/*.whl
